// Auth
const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_ERROR = 'LOGIN_ERROR';
const REGISTER_REQUESTED = 'REGISTER_REQUESTED';

// Get User
const GET_USER_DATA = 'GET_USER_DATA';
const SET_USER_DATA = 'SET_USER_DATA';

// Search for Users
const CONTACTS_REQUESTED = 'CONTACTS_REQUESTED';
const SET_FOUND_CONTACTS = 'SET_FOUND_CONTACTS';
const CONTACTS_NOT_FOUND = 'CONTACTS_NOT_FOUND';

// Clear Errors
const CLEAR_ERROR_USER = 'CLEAR_ERROR_USER';

const DEALOGS_REQUESTED = 'DEALOGS_REQUESTED';
const DIALOGS_LOAD_SUCCESS = 'DIALOGS_LOAD_SUCCESS';
const SET_DIALOG = 'SET_DIALOG';

const MESSAGES_REQUESTED = 'MESSAGES_REQUESTED';
const MESSAGES_LOAD_SUCCESS = 'MESSAGES_LOAD_SUCCESS';
const SEND_MESSAGE = 'SEND_MESSAGE';
const GET_MESSAGE = 'GET_MESSAGE';
const DELETE_MESSAGE = 'DELETE_MESSAGE';

export {
  LOGIN_REQUESTED,
  LOGIN_SUCCESS,
  LOGIN_ERROR,
  GET_USER_DATA,
  SET_USER_DATA,
  REGISTER_REQUESTED,
  CLEAR_ERROR_USER,
  DEALOGS_REQUESTED,
  DIALOGS_LOAD_SUCCESS,
  SET_DIALOG,
  MESSAGES_REQUESTED,
  MESSAGES_LOAD_SUCCESS,
  SEND_MESSAGE,
  GET_MESSAGE,
  DELETE_MESSAGE,
  CONTACTS_REQUESTED,
  SET_FOUND_CONTACTS,
  CONTACTS_NOT_FOUND
}