const DEALOGS_REQUESTED = 'DEALOGS_REQUESTED';
const DIALOGS_LOAD_SUCCESS = 'DIALOGS_LOAD_SUCCESS';
const DIALOG_ID = 'DIALOG_ID';

const MESSAGES_REQUESTED = 'MESSAGES_REQUESTED';
const MESSAGES_LOAD_SUCCESS = 'MESSAGES_LOAD_SUCCESS';

export {
  DEALOGS_REQUESTED,
  DIALOGS_LOAD_SUCCESS,
  DIALOG_ID,
  MESSAGES_REQUESTED,
  MESSAGES_LOAD_SUCCESS
}