export const socketEvents = {
  CONNECTED_USER: 'CONNECTED_USER',
  DIALOG_JOIN: 'DIALOG_JOIN',
  DIALOG_RECEIVED: 'DIALOG_RECEIVED',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  MESSAGES_RECEIVED: 'MESSAGES_RECEIVED',
  MESSAGES_READED: 'MESSAGES_READED',
  MESSAGES_NO_READ: 'MESSAGES_NO_READ',
  DELETE_MESSAGE: 'DELETE_MESSAGE',
  MESSAGE_EDITING: 'MESSAGE_EDITING',
  LAST_MESSAGE: 'LAST_MESSAGE',
  TYPING_MESSAGE: 'TYPING_MESSAGE',
  STATUS_ONLINE: 'STATUS_ONLINE'
}