export const socketEvents = {
  CONNECTED_USER: 'CONNECTED_USER',
  DIALOG_JOIN: 'DIALOG_JOIN',
  DIALOG_RECEIVED: 'DIALOG_RECEIVED',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  MESSAGES_READED: 'MESSAGES_READED',
  TYPING_MESSAGE: 'TYPING_MESSAGE',
  STATUS_ONLINE: 'STATUS_ONLINE'
}